Implement XDG base dir
agrawal-d/moodle-cms-notifs pull request #2
Opened 2021-06-12 19:31 UTC by p00f

Closes #1

2021-06-12 19:35 UTC, p00f commented
`env::consts::OS` has these possible values:
https://doc.rust-lang.org/std/env/consts/constant.OS.html

 I tested this with a custom `XDG_STATE_HOME` and with `XDG_STATE_HOME` unset. Didn't test `XDG_CONFIG_HOME` but it's the same thing

2021-06-12 19:54 UTC, p00f commented
Wait I forgot to document it

2021-06-12 20:04 UTC, p00f commented
Done

2021-06-13 13:58 UTC, agrawal-d requested changes
Thanks for the PR @p00f . I left some minor comments. Otherwise, the code looks good.
I think it's reasonable to keep the documentation and the code change in the same commit since they are closely coupled.

However, you should fix the typos in a separate commit as I have explained in the review.

2021-06-13 13:58 UTC, agrawal-d commented on README.md
> +along with this program.  If not, see <https://www.gnu.org/licenses/>.
Did you change something here? Maybe the line ending? Please revert this.

2021-06-13 13:58 UTC, agrawal-d commented on README.md
> +## Config file and logs
```suggestion
## Location of configuration and log files
```

2021-06-13 13:58 UTC, agrawal-d commented on src/lib.rs
> +    /// Get the path where the config file should be saved.
Each commit should be a self-contained change. This change is not related to the main goal of the PR - to implement XDG base dir. So, for each logical unit of code change, you should create a separate commit, with a descriptive commit message explaining the motive of the change.

Also, this is a non-functional change. Usually, its better to label such changes as NFC. 

So, you can create a separate commit for all these typo fixes and a commit message for this commit can be:

```
[NFC] Fix typos in comments.

Fix various typos within comments.
```

You can use an interactive rebase ( https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase ) to make changes to existing commits, if you wish to.

2021-06-13 13:58 UTC, agrawal-d commented on src/lib.rs
> +        }
Instead of having a mutable variable and then modifying it, I think it's better to use a single expression.

```
let config_path = {
   // some code
   final_value
};
```

This helps remove the `mut` and also groups together a block of logic, making the code cleaner.

2021-06-13 13:58 UTC, agrawal-d commented on src/main.rs
> +    }
Same as above.

2021-06-13 13:59 UTC, agrawal-d commented on src/lib.rs
> +                Ok(())
I noticed later, this block of change should also be in a separate commit, since it is not related to the feature you are implementing.

2021-06-13 14:05 UTC, p00f commented
Thanks for the tips! I'll create another PR with the suggested changes

2021-06-13 14:06 UTC, agrawal-d requested changes
Some additional comments.

2021-06-13 14:06 UTC, agrawal-d commented on src/main.rs
> +    static LOGS_STORE_LOCATION: &str = ".cms_notifs.log"; // The location where the logs are stored.
This comment is no longer true, right? I think you should change the comment to match what this variable means now. Same goes for line 19 in `lib.rs`.

2021-06-13 14:06 UTC, agrawal-d commented on src/main.rs
> +    static LOGS_STORE_LOCATION: &str = ".cms_notifs.log"; // The location where the logs are stored.
Also, I think you should log ( `!info` ) where the logs are being stored, and where the config is being read from.

2021-06-13 14:10 UTC, agrawal-d commented
@p00f no need to close the PR. After making the changes and modifying the commits, you can force-push your changes.

Some projects prefer to add commits on top of a PR and squash them in the end, but I prefer to retain the original commits.

2021-06-13 14:11 UTC, p00f commented on src/main.rs
> +    static LOGS_STORE_LOCATION: &str = ".cms_notifs.log"; // The location where the logs are stored.
> This comment is no longer true, right? I think you should change the comment to match what this variable means now. Same goes for line 19 in lib.rs.

I wanted to ask about this, since the variable name `LOGS_STORE_LOCATION` no longer means what it says on Linux, should I remove the static and do everything inside
```rust
let log_location = match env::consts::OS {
    "linux" => (...)
    _ => (...)
}
```
? Because in the end we only want the log file path and not the directory.

2021-06-13 14:12 UTC, agrawal-d commented on src/main.rs
> +    static LOGS_STORE_LOCATION: &str = ".cms_notifs.log"; // The location where the logs are stored.
Yeah, sounds good.

2021-06-13 14:30 UTC, p00f commented on README.md
> +along with this program.  If not, see <https://www.gnu.org/licenses/>.
![image](https://user-images.githubusercontent.com/36493671/121811369-dcab6680-cc81-11eb-8ed5-1d87bcc00603.png)

There was originally no line ending at EOF. Do you want me to revert this?

2021-06-13 14:58 UTC, agrawal-d commented on README.md
> +along with this program.  If not, see <https://www.gnu.org/licenses/>.
I see. It's fine, let it stay ( as a separate commit ).

2021-06-13 15:09 UTC, p00f commented on README.md
> +along with this program.  If not, see <https://www.gnu.org/licenses/>.
I'm doing this https://stackoverflow.com/questions/1440050/how-to-split-last-commit-into-two-in-git so I already deleted those commits (with changes intact). Do you want the newline and doc change in the same commit?

2021-06-13 15:51 UTC, p00f commented
![image](https://user-images.githubusercontent.com/36493671/121814182-4da44b80-cc8d-11eb-954b-bdeae3be05a3.png)
Logging is like this

2021-06-13 16:11 UTC, agrawal-d requested changes
Looks good now! Just one minor change is needed -  all the changes related to the XDG base dir feature should be in the same commit.

Also, did you forget to include the Webview match block fix?

2021-06-13 16:11 UTC, agrawal-d commented on README.md
> +## Location of configuration and log files
This change should be in the same commit as the one that implements the XDG base dir feature.

2021-06-13 16:11 UTC, agrawal-d commented on src/lib.rs
> +            info!("Config file does not exist, creating a new file.");
This change should be in the same commit as the one that implements the XDG base dir feature.

2021-06-13 16:12 UTC, merged

2021-06-13 16:12 UTC, agrawal-d commented
I merged the changes, as the modifications needed were very minor. 

If you want to, you can still send in a patch for the Webview match block that you fixed.


Thanks a lot for your work!

2021-06-13 17:13 UTC, p00f commented
> Also, did you forget to include the Webview match block fix?

The other day (on discord) you said there might have been a reason so I didn't include it this time